// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/exp/mu2e/app/users/aboldy/AnaDir/SimulationTestingFall25/AnalysisCode/Plots/MDC2020ba/MCParticlesTest/CeEndpoint/./../../../../plotElectronMomHist.C";

#endif
